In [2]:
import pandas as pd


df = pd.read_csv('Analysis_Data/drinks.csv')
df

FileNotFoundError: [Errno 2] File b'Analysis_Data/drinks.csv' does not exist: b'Analysis_Data/drinks.csv'

In [3]:
import pandas as pd


df = pd.read_csv('Analysis_Data/drinks.csv')
df

FileNotFoundError: [Errno 2] File b'Analysis_Data/drinks.csv' does not exist: b'Analysis_Data/drinks.csv'

In [4]:
import os
os.getcwd()

'C:\\Users\\student205.AUTOLAB2\\Documents\\Szczesny\\LAB1 Drinks\\Command_Files'

In [5]:
import pandas as pd


df = pd.read_csv('../Analysis_Data/drinks.csv')
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9
5,Antigua & Barbuda,102,128,45,4.9
6,Argentina,193,25,221,8.3
7,Armenia,21,179,11,3.8
8,Australia,261,72,212,10.4
9,Austria,279,75,191,9.7
10,Azerbaijan,21,46,5,1.3
11,Bahamas,122,176,51,6.3
12,Bahrain,42,63,7,2.0
13,Bangladesh,0,0,0,0.0
14,Barbados,143,173,36,6.3
15,Belarus,142,373,42,14.4
16,Belgium,295,84,212,10.5
17,Belize,263,114,8,6.8
18,Benin,34,4,13,1.1
19,Bhutan,23,0,0,0.4
20,Bolivia,167,41,8,3.8
21,Bosnia-Herzegovina,76,173,8,4.6
22,Botswana,173,35,35,5.4
23,Brazil,245,145,16,7.2
24,Brunei,31,2,1,0.6
25,Bulgaria,231,252,94,10.3
26,Burkina Faso,25,7,7,4.3
27,Burundi,88,0,0,6.3
28,Cote d'Ivoire,37,1,7,4.0
29,Cabo Verde,144,56,16,4.0
...,...,...,...,...,...
163,Suriname,128,178,7,5.6
164,Swaziland,90,2,2,4.7
165,Sweden,152,60,186,7.2
166,Switzerland,185,100,280,10.2
167,Syria,5,35,16,1.0
168,Tajikistan,2,15,0,0.3
169,Thailand,99,258,1,6.4
170,Macedonia,106,27,86,3.9
171,Timor-Leste,1,1,4,0.1
172,Togo,36,2,19,1.3
173,Tonga,36,21,5,1.1
174,Trinidad & Tobago,197,156,7,6.4
175,Tunisia,51,3,20,1.3
176,Turkey,51,22,7,1.4
177,Turkmenistan,19,71,32,2.2
178,Tuvalu,6,41,9,1.0
179,Uganda,45,9,0,8.3
180,Ukraine,206,237,45,8.9
181,United Arab Emirates,16,135,5,2.8
182,United Kingdom,219,126,195,10.4
183,Tanzania,36,6,1,5.7
184,USA,249,158,84,8.7
185,Uruguay,115,35,220,6.6
186,Uzbekistan,25,101,8,2.4
187,Vanuatu,21,18,11,0.9
188,Venezuela,333,100,3,7.7
189,Vietnam,111,2,1,2.0
190,Yemen,6,0,0,0.1
191,Zambia,32,19,4,2.5
192,Zimbabwe,64,18,4,4.7

In [6]:
import pandas as pd


df = pd.read_csv('../Analysis_Data/drinks.csv')
df = df.sort_values(by='country')
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9
5,Antigua & Barbuda,102,128,45,4.9
6,Argentina,193,25,221,8.3
7,Armenia,21,179,11,3.8
8,Australia,261,72,212,10.4
9,Austria,279,75,191,9.7
10,Azerbaijan,21,46,5,1.3
11,Bahamas,122,176,51,6.3
12,Bahrain,42,63,7,2.0
13,Bangladesh,0,0,0,0.0
14,Barbados,143,173,36,6.3
15,Belarus,142,373,42,14.4
16,Belgium,295,84,212,10.5
17,Belize,263,114,8,6.8
18,Benin,34,4,13,1.1
19,Bhutan,23,0,0,0.4
20,Bolivia,167,41,8,3.8
21,Bosnia-Herzegovina,76,173,8,4.6
22,Botswana,173,35,35,5.4
23,Brazil,245,145,16,7.2
24,Brunei,31,2,1,0.6
25,Bulgaria,231,252,94,10.3
26,Burkina Faso,25,7,7,4.3
27,Burundi,88,0,0,6.3
29,Cabo Verde,144,56,16,4.0
30,Cambodia,57,65,1,2.2
...,...,...,...,...,...
162,Sudan,8,13,0,1.7
163,Suriname,128,178,7,5.6
164,Swaziland,90,2,2,4.7
165,Sweden,152,60,186,7.2
166,Switzerland,185,100,280,10.2
167,Syria,5,35,16,1.0
168,Tajikistan,2,15,0,0.3
183,Tanzania,36,6,1,5.7
169,Thailand,99,258,1,6.4
171,Timor-Leste,1,1,4,0.1
172,Togo,36,2,19,1.3
173,Tonga,36,21,5,1.1
174,Trinidad & Tobago,197,156,7,6.4
175,Tunisia,51,3,20,1.3
176,Turkey,51,22,7,1.4
177,Turkmenistan,19,71,32,2.2
178,Tuvalu,6,41,9,1.0
184,USA,249,158,84,8.7
179,Uganda,45,9,0,8.3
180,Ukraine,206,237,45,8.9
181,United Arab Emirates,16,135,5,2.8
182,United Kingdom,219,126,195,10.4
185,Uruguay,115,35,220,6.6
186,Uzbekistan,25,101,8,2.4
187,Vanuatu,21,18,11,0.9
188,Venezuela,333,100,3,7.7
189,Vietnam,111,2,1,2.0
190,Yemen,6,0,0,0.1
191,Zambia,32,19,4,2.5
192,Zimbabwe,64,18,4,4.7

In [20]:
import pandas as pd


df = pd.read_csv('../Analysis_Data/drinks.csv')
df = df.drop('total_litres_of_pure_alcohol', axis=1)
df_beer = df[['country', 'beer_servings']]
df_spirit = df[['country', 'spirit_servings']]
df_wine = df[['country', 'wine_servings']]
df_beer.to_csv('../Analysis_Data/drinks_beer.csv', index=False)
df_spirit.to_csv('../Analysis_Data/drinks_spirit.csv', index=False)
df_wine.to_csv('../Analysis_Data/drinks_wine.csv', index=False)

df_test = pd.melt(df, id_vars=['country'], value_vars=['beer_servings','spirit_servings','wine_servings'])
df_test = df_test.sort_values(by='country')
df_test.to_csv('../Analysis_Data/df_tidy.csv', index=False)
df_test

                  country         variable  value
0             Afghanistan    beer_servings      0
193           Afghanistan  spirit_servings      0
386           Afghanistan    wine_servings      0
1                 Albania    beer_servings     89
194               Albania  spirit_servings    132
387               Albania    wine_servings     54
2                 Algeria    beer_servings     25
195               Algeria  spirit_servings      0
388               Algeria    wine_servings     14
196               Andorra  spirit_servings    138
389               Andorra    wine_servings    312
3                 Andorra    beer_servings    245
390                Angola    wine_servings     45
4                  Angola    beer_servings    217
197                Angola  spirit_servings     57
391     Antigua & Barbuda    wine_servings     45
5       Antigua & Barbuda    beer_servings    102
198     Antigua & Barbuda  spirit_servings    128
392             Argentina    wine_servings    221
199             Argentina  spirit_servings     25
6               Argentina    beer_servings    193
200               Armenia  spirit_servings    179
393               Armenia    wine_servings     11
7                 Armenia    beer_servings     21
201             Australia  spirit_servings     72
394             Australia    wine_servings    212
8               Australia    beer_servings    261
395               Austria    wine_servings    191
9                 Austria    beer_servings    279
202               Austria  spirit_servings     75
..                    ...              ...    ...
181  United Arab Emirates    beer_servings     16
374  United Arab Emirates  spirit_servings    135
567  United Arab Emirates    wine_servings      5
182        United Kingdom    beer_servings    219
568        United Kingdom    wine_servings    195
375        United Kingdom  spirit_servings    126
571               Uruguay    wine_servings    220
185               Uruguay    beer_servings    115
378               Uruguay  spirit_servings     35
572            Uzbekistan    wine_servings      8
186            Uzbekistan    beer_servings     25
379            Uzbekistan  spirit_servings    101
187               Vanuatu    beer_servings     21
380               Vanuatu  spirit_servings     18
573               Vanuatu    wine_servings     11
574             Venezuela    wine_servings      3
188             Venezuela    beer_servings    333
381             Venezuela  spirit_servings    100
189               Vietnam    beer_servings    111
382               Vietnam  spirit_servings      2
575               Vietnam    wine_servings      1
190                 Yemen    beer_servings      6
576                 Yemen    wine_servings      0
383                 Yemen  spirit_servings      0
384                Zambia  spirit_servings     19
577                Zambia    wine_servings      4
191                Zambia    beer_servings     32
192              Zimbabwe    beer_servings     64
385              Zimbabwe  spirit_servings     18
578              Zimbabwe    wine_servings      4

[579 rows x 3 columns]